---
- name: Setting up local environment
  hosts: bastions
  tasks:
    - name: Creating backup directory
      ansible.builtin.file:
        path: "{{ directory.backup }}"
        state: directory

- name: Checking APIManager instance status
  hosts: bastions
  tasks:
    - name: Retrieve APIManager instance information
      kubernetes.core.k8s_info:
        api_version: apps.3scale.net/v1alpha1
        kind: APIManager
        namespace: "{{ project.threescale }}"
      register: apimanager_crd
    - name: Stop if the APIManager instance was not found
      ansible.builtin.fail:
        msg: "No APIManager instances found"
      when: not apimanager_crd.api_found
    - name: Saving APIManager instance definition
      ansible.builtin.copy:
        content: "{{ apimanager_crd.resources[0] | to_yaml }}"
        dest: "{{ directory.backup }}/apimanager.yaml"
      no_log: true
    - name: Saving APIManager instance definition
      set_fact:
        apimanager: "{{ apimanager_crd.resources[0] }}"

- name: Retrieve information for all pods with persistence
  hosts: bastions
  tasks:
    - name: Creating a variable to store the information
      ansible.builtin.set_fact:
        pods: {}
    - name: Populate the variable with all relevant Pods' information
      include_tasks: resources.yaml
      with_items:
        - key: MySQL
          label: system-mysql
        - key: System (app)
          label: system-app
        - key: Redis (backend)
          label: backend-redis
        - key: Redis (system)
          label: system-redis
        - key: Zync (database)
          label: zync-database

- name: Checking connectivity with external systems
  hosts: bastions
  tasks:
    - name: Running a test query against the external MySQL
      kubernetes.core.k8s_exec:
        command: >
          mysql -u{{ external.mysql.user }} -h {{ external.mysql.host }} -p{{ external.mysql.password }} -e '{{ external.mysql.test_query }};' {{ external.mysql.database }}
        namespace: "{{ project.threescale }}"
        pod: "{{ pods['MySQL'].metadata.name }}"
      register: query_output
    - name: Stop if the test query fails
      ansible.builtin.fail:
        msg: "Connection attempt to external MySQL failed"
      when: query_output.rc != 0

- name: Save all information to handle a potential recovery
  hosts: bastions
  tasks:
    - name: Saving System (storage) contents
      kubernetes.core.k8s_cp:
        container: system-master
        local_path: "{{ directory.backup }}"
        namespace: "{{ project.threescale }}"
        pod: "{{ pods['System (app)'].metadata.name }}"
        remote_path: /opt/system/public/system
        state: from_pod
    - name: Saving Redis (backend) contents
      kubernetes.core.k8s_cp:
        local_path: "{{ directory.backup }}/backend-redis-dump.rdb"
        namespace: "{{ project.threescale }}"
        pod: "{{ pods['Redis (backend)'].metadata.name }}"
        remote_path: /var/lib/redis/data/dump.rdb
        state: from_pod
    - name: Saving Redis (system) contents
      kubernetes.core.k8s_cp:
        local_path: "{{ directory.backup }}/system-redis-dump.rdb"
        namespace: "{{ project.threescale }}"
        pod: "{{ pods['Redis (system)'].metadata.name }}"
        remote_path: /var/lib/redis/data/dump.rdb
        state: from_pod
    - name: Extracting Zync (database) contents
      kubernetes.core.k8s_exec:
        command: >
          bash -c 'pg_dump zync_production'
        namespace: "{{ project.threescale }}"
        pod: "{{ pods['Zync (database)'].metadata.name }}"
      register: zync_dump
    - name: Saving Zync (database) contents locally
      ansible.builtin.copy:
        content: "{{ zync_dump.stdout }}"
        dest: "{{ directory.backup }}/zync-database.sql"
      no_log: true
    - name: Extracting System (database) contents
      kubernetes.core.k8s_exec:
        command: >
          bash -c 'export MYSQL_PWD=${MYSQL_ROOT_PASSWORD}; mysqldump --single-transaction -hsystem-mysql -uroot system'
        namespace: "{{ project.threescale }}"
        pod: "{{ pods['MySQL'].metadata.name }}"
      register: system_dump
    - name: Saving System (database) contents locally
      ansible.builtin.copy:
        content: "{{ system_dump.stdout }}"
        dest: "{{ directory.backup }}/system-mysql.sql"
      no_log: true
    - name: Refactor content to be agnostic of the creator
      ansible.builtin.replace:
        path: "{{ directory.backup }}/system-mysql.sql"
        regexp: "DEFINER=`root`@`%`"
        replace: ""
    - name: Saving all ConfigMaps
      include_tasks: configurations.yaml
      with_items:
        - name: system-environment
          kind: ConfigMap
        - name: apicast-environment
          kind: ConfigMap
    - name: Saving all Secrets
      include_tasks: configurations.yaml
      with_items:
        - name: system-smtp
          kind: Secret
        - name: system-seed
          kind: Secret
        - name: system-database
          kind: Secret
        - name: backend-internal-api
          kind: Secret
        - name: system-events-hook
          kind: Secret
        - name: system-recaptcha
          kind: Secret
        - name: system-redis
          kind: Secret
        - name: zync
          kind: Secret
        - name: system-master-apicast
          kind: Secret

- name: Scaling all replicas to zero
  hosts: bastions
  tasks:
    - name: Scale all DeploymentConfigs to zero
      include_tasks: scaling.yaml
      vars:
        replicas: 0
      with_items: "{{ deployments.elements }}"

- name: Import the dump into the external server
  hosts: bastions
  tasks:
    - name: Import locally saved contents to the external MySQL
      community.mysql.mysql_db:
        login_host: "{{ external.mysql.other_host | default(external.mysql.host, true) }}"
        login_password: "{{ external.mysql.password }}"
        login_port: "{{ external.mysql.other_port | default(external.mysql.port, true) }}"
        login_user: "{{ external.mysql.user }}"
        name: "{{ external.mysql.database }}"
        state: import
        target: "{{ directory.backup }}/system-mysql.sql"

- name: Update the connection strings
  hosts: bastions
  tasks:
    - name: Update the connection string to point to the external MySQL
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: system-database
            namespace: "{{ project.threescale }}"
          stringData:
            URL: "mysql2://{{ external.mysql.user }}:{{ external.mysql.password }}@{{ external.mysql.host }}/{{ external.mysql.database }}"
        state: patched
    - name: Updating connection parameters for Redis (system)
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: system-redis
            namespace: "{{ project.threescale }}"
          stringData:
            URL: "redis://:{{ external.redis.system.password }}@{{ external.redis.system.host }}:{{ external.redis.system.port }}"
    - name: Updating connection parameters for Redis (backend)
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: backend-redis
            namespace: "{{ project.threescale }}"
          stringData:
            REDIS_QUEUES_URL: "redis://:{{ external.redis.backend.queues.password }}@{{ external.redis.backend.queues.host }}:{{ external.redis.backend.queues.port }}"
            REDIS_STORAGE_URL: "redis://:{{ external.redis.backend.storage.password }}@{{ external.redis.backend.storage.host }}:{{ external.redis.backend.storage.port }}"

- name: Updating Operator resources
  hosts: bastions
  tasks:
    - name: "Updating Custom Resource Definition (CRD)"
      kubernetes.core.k8s:
        definition:
          apiVersion: apps.3scale.net/v1alpha1
          kind: APIManager
          metadata:
            name: "{{ apimanager.metadata.name }}"
            namespace: "{{ project.threescale }}"
          spec:
            externalComponents:
              backend:
                redis: true
              system:
                database: true
                redis: true
        state: patched

- name: Scaling up all replicas
  hosts: bastions
  tasks:
    - name: Scale up all DeploymentConfigs
      include_tasks: scaling.yaml
      vars:
        replicas: "{{ item.replicas | default(1, true) }}"
      with_items: "{{ deployments.elements | rejectattr('name', 'in', ['backend-redis', 'system-mysql', 'system-redis']) | list | reverse }}"
