apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql-tmp
  namespace: dbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password_di_test
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_USER
              value: test
            - name: MYSQL_PASSWORD
              value: Test123!
          image: mysql:8.0
          args:
            - "--skip-name-resolve"
            - "--default-authentication-plugin=mysql_native_password"
            - "--authentication-policy=mysql_native_password"
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: temp-storage
      volumes:
        - emptyDir: {}
          name: temp-storage
