ansible_connection: local
ansible_host: localhost
ansible_python_interpreter: "{{ ansible_playbook_python }}"
project:
  threescale: "3scale"
external:
  components:
    mysql:
      name: mysql
      password: "Password123!"
      project: dbms
      storage:
        size: 8Gi
      user: root
    valkey:
      - name: backend
        password: "Pippo123!"
        project: dbms
        storage:
          size: 1Gi
      - name: system
        password: "Pippo123!"
        project: dbms
        storage:
          size: 1Gi
  mysql:
    database: testdb
    host: mysql.dbms.svc.cluster.local
    other_host: 127.0.0.1
    password: "Password123!"
    port: 3306
    user: root
  redis:
    backend:
      queues:
        host: valkey-backend.dbms.svc.cluster.local
        port: 6379
        password: "Pippo123!"
      storage:
        host: valkey-backend.dbms.svc.cluster.local
        port: 6379
        password: "Pippo123!"
    system:
      host: valkey-system.dbms.svc.cluster.local
      port: 6379
      password: "Pippo123!"
