apiVersion: v1
data: {rht_backend_redis_requirements: 6.2.0, rht_mysql_requirements: 8.0.0, rht_postgres_requirements: 10.0.0,
  rht_system_redis_requirements: 6.2.0, rht_threescale_version_requirements: '2.15'}
kind: ConfigMap
metadata:
  creationTimestamp: '2026-09-10T14:41:06Z'
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:rht_backend_redis_requirements: {}
        f:rht_mysql_requirements: {}
        f:rht_postgres_requirements: {}
        f:rht_system_redis_requirements: {}
        f:rht_threescale_version_requirements: {}
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"4c3f9b0d-2e86-4f03-b112-2acc4bfaac4b"}: {}
    manager: manager
    operation: Update
    time: '2026-09-10T14:41:06Z'
  name: 3scale-api-management-operator-requirements
  namespace: 3scale
  ownerReferences:
  - {apiVersion: operators.coreos.com/v1alpha1, kind: Subscription, name: 3scale-operator,
    uid: 4c3f9b0d-2e86-4f03-b112-2acc4bfaac4b}
  resourceVersion: '3041506796'
  uid: 9bfe549b-c8bd-4409-8056-6134e85b682a
