apiVersion: v1
data:
  REDIS_QUEUES_SENTINEL_HOSTS: ""
  REDIS_QUEUES_SENTINEL_ROLE: ""
  REDIS_QUEUES_URL: cmVkaXM6Ly9iYWNrZW5kLXJlZGlzOjYzNzkvMQ==
  REDIS_STORAGE_SENTINEL_HOSTS: ""
  REDIS_STORAGE_SENTINEL_ROLE: ""
  REDIS_STORAGE_URL: cmVkaXM6Ly9iYWNrZW5kLXJlZGlzOjYzNzkvMA==
kind: Secret
metadata:
  labels:
    app: 3scale-api-management
    threescale_component: backend
  name: backend-redis
  namespace: 3scale
type: Opaque
