apiVersion: v1
data:
  SENTINEL_HOSTS: ""
  SENTINEL_ROLE: ""
  URL: cmVkaXM6Ly9zeXN0ZW0tcmVkaXM6NjM3OS8x
kind: Secret
metadata:
  labels:
    app: 3scale-api-management
    threescale_component: system
  name: system-redis
  namespace: 3scale
type: Opaque
