apiVersion: v1
data:
  DB_PASSWORD: bjVXWlV6Y2U=
  DB_USER: bXlzcWw=
  URL: bXlzcWwyOi8vcm9vdDpWQ1VzQ0tXZUBzeXN0ZW0tbXlzcWwvc3lzdGVt
kind: Secret
metadata:
  labels:
    app: 3scale-api-management
    threescale_component: system
  name: system-database
  namespace: 3scale
type: Opaque
