ansible_connection: local
ansible_host: localhost
ansible_python_interpreter: "{{ ansible_playbook_python }}"
project:
  threescale: "3scale"
external:
  mysql:
    database: 3scaleocp1v_mysql
    host: 26.0.133.193
    #other_host: 127.0.0.1   ### DA ABILITARE SOLO PER TUNNELING # ssh -vv -N   -L 127.0.0.1:9000:{MYSQL_DB_HOST}:{MYSQL_DB_PORT}   core@{OCP4_WORKER_NODE}
    password: 'Pzm_(6202)'
    port: 3306
    #other_port: 9000      ### DA ABILITARE SOLO PER TUNNELING # ssh -vv -N   -L 127.0.0.1:9000:{MYSQL_DB_HOST}:{MYSQL_DB_PORT}   core@{OCP4_WORKER_NODE}
    user: appl_3scale_ocp1v
  redis:
    backend:
      queues:
        host: redis-15528.redisvalclu02.sogei.it
        port: 15528
        password: "P0CR3D3ScaleBK01"
      storage:
        host: redis-12614.redisvalclu02.sogei.it
        port: 12614
        password: "P0CR3D3ScaleBK00"
    system:
      host: redis-10233.redisvalclu02.sogei.it
      port: 10233
      password: "P0CR3D3ScaleSY00"
